apiVersion: v1
kind: Service
metadata:
  name: myportal-svc
  labels:
    name: myportal
spec:
  ports:
  - port: 27080
    targetPort: 80
    nodePort: 30001
    protocol: TCP
  selector:
    name: myportal
  type: NodePort


